"""layer3_event_infrastructure

Revision ID: 0da24644e00d
Revises: 302d049bf01d
Create Date: 2026-04-12 12:00:10.530274

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0da24644e00d'
down_revision: Union[str, Sequence[str], None] = '302d049bf01d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scrape_jobs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('source', sa.Text(), nullable=False),
    sa.Column('status', sa.Text(), server_default=sa.text("'running'"), nullable=False),
    sa.Column('companies_found', sa.Integer(), server_default=sa.text('0'), nullable=True),
    sa.Column('companies_new', sa.Integer(), server_default=sa.text('0'), nullable=True),
    sa.Column('companies_updated', sa.Integer(), server_default=sa.text('0'), nullable=True),
    sa.Column('companies_duplicate', sa.Integer(), server_default=sa.text('0'), nullable=True),
    sa.Column('query', sa.Text(), nullable=True),
    sa.Column('batch', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_scrape_jobs_source', 'scrape_jobs', ['source', 'started_at'], unique=False)
    op.create_index('idx_scrape_jobs_status', 'scrape_jobs', ['status'], unique=False)
    op.create_table('events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('event_type', sa.Text(), nullable=False),
    sa.Column('firm_id', sa.UUID(), nullable=True),
    sa.Column('member_id', sa.UUID(), nullable=True),
    sa.Column('entity_type', sa.Text(), nullable=True),
    sa.Column('entity_id', sa.UUID(), nullable=True),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'"), nullable=False),
    sa.Column('webhook_id', sa.Text(), nullable=True),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('processing_attempts', sa.Integer(), server_default=sa.text('0'), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['firm_id'], ['firms.id'], ),
    sa.ForeignKeyConstraint(['member_id'], ['firm_members.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('webhook_id')
    )
    op.create_index('idx_events_entity', 'events', ['entity_type', 'entity_id'], unique=False)
    op.create_index('idx_events_firm', 'events', ['firm_id'], unique=False, postgresql_where=sa.text('firm_id IS NOT NULL'))
    op.create_index('idx_events_type', 'events', ['event_type'], unique=False)
    op.create_index('idx_events_unprocessed', 'events', ['created_at'], unique=False, postgresql_where=sa.text('processed_at IS NULL'))
    op.create_index('idx_events_webhook_id', 'events', ['webhook_id'], unique=True, postgresql_where=sa.text('webhook_id IS NOT NULL'))
    op.create_table('agent_runs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('agent_type', sa.Text(), nullable=False),
    sa.Column('trigger_event_id', sa.UUID(), nullable=True),
    sa.Column('firm_id', sa.UUID(), nullable=True),
    sa.Column('entity_type', sa.Text(), nullable=True),
    sa.Column('entity_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.Text(), server_default=sa.text("'running'"), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('actions_taken', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'"), nullable=False),
    sa.Column('output_summary', sa.Text(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('retry_count', sa.Integer(), server_default=sa.text('0'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['firm_id'], ['firms.id'], ),
    sa.ForeignKeyConstraint(['trigger_event_id'], ['events.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_agent_runs_firm', 'agent_runs', ['firm_id'], unique=False, postgresql_where=sa.text('firm_id IS NOT NULL'))
    op.create_index('idx_agent_runs_status', 'agent_runs', ['status', 'started_at'], unique=False)
    op.create_index('idx_agent_runs_trigger', 'agent_runs', ['trigger_event_id'], unique=False)
    op.create_index('idx_agent_runs_type', 'agent_runs', ['agent_type'], unique=False)
    # Deferred FK: firm_notifications.related_event_id → events.id
    # This constraint was intentionally deferred to Layer 3 to avoid a
    # forward-reference from Layer 2 to the events table.
    op.create_foreign_key(
        'fk_firm_notifications_related_event_id',
        'firm_notifications', 'events',
        ['related_event_id'], ['id']
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Drop the deferred FK before dropping the events table
    op.drop_constraint(
        'fk_firm_notifications_related_event_id',
        'firm_notifications', type_='foreignkey'
    )
    op.drop_index('idx_agent_runs_type', table_name='agent_runs')
    op.drop_index('idx_agent_runs_trigger', table_name='agent_runs')
    op.drop_index('idx_agent_runs_status', table_name='agent_runs')
    op.drop_index('idx_agent_runs_firm', table_name='agent_runs', postgresql_where=sa.text('firm_id IS NOT NULL'))
    op.drop_table('agent_runs')
    op.drop_index('idx_events_webhook_id', table_name='events', postgresql_where=sa.text('webhook_id IS NOT NULL'))
    op.drop_index('idx_events_unprocessed', table_name='events', postgresql_where=sa.text('processed_at IS NULL'))
    op.drop_index('idx_events_type', table_name='events')
    op.drop_index('idx_events_firm', table_name='events', postgresql_where=sa.text('firm_id IS NOT NULL'))
    op.drop_index('idx_events_entity', table_name='events')
    op.drop_table('events')
    op.drop_index('idx_scrape_jobs_status', table_name='scrape_jobs')
    op.drop_index('idx_scrape_jobs_source', table_name='scrape_jobs')
    op.drop_table('scrape_jobs')
    # ### end Alembic commands ###
