"""layer2_per_firm_intelligence

Revision ID: 302d049bf01d
Revises: d623b43ffd99
Create Date: 2026-04-11 16:19:56.988420

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from pgvector.sqlalchemy import Vector

# revision identifiers, used by Alembic.
revision: str = '302d049bf01d'
down_revision: Union[str, Sequence[str], None] = 'd623b43ffd99'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('firms',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('slug', sa.Text(), nullable=False),
    sa.Column('website', sa.Text(), nullable=True),
    sa.Column('clerk_org_id', sa.Text(), nullable=True),
    sa.Column('owner_user_id', sa.Text(), nullable=False),
    sa.Column('thesis_text', sa.Text(), nullable=True),
    sa.Column('focus_stages', postgresql.ARRAY(sa.Text()), server_default='{}', nullable=False),
    sa.Column('focus_sectors', postgresql.ARRAY(sa.Text()), server_default='{}', nullable=False),
    sa.Column('focus_geographies', postgresql.ARRAY(sa.Text()), server_default='{}', nullable=False),
    sa.Column('check_size_min_usd', sa.BigInteger(), nullable=True),
    sa.Column('check_size_max_usd', sa.BigInteger(), nullable=True),
    sa.Column('excluded_sectors', postgresql.ARRAY(sa.Text()), server_default='{}', nullable=False),
    sa.Column('excluded_business_models', postgresql.ARRAY(sa.Text()), server_default='{}', nullable=False),
    sa.Column('ai_nativeness_min', sa.SmallInteger(), server_default='1', nullable=True),
    sa.Column('coverage_threshold', sa.SmallInteger(), server_default='3', nullable=True),
    sa.Column('portfolio_companies', postgresql.ARRAY(sa.Text()), nullable=True),
    sa.Column('notable_investments', postgresql.ARRAY(sa.Text()), nullable=True),
    sa.Column('typical_pass_reasons', postgresql.ARRAY(sa.Text()), nullable=True),
    sa.Column('notification_emails', postgresql.ARRAY(sa.Text()), server_default='{}', nullable=False),
    sa.Column('weekly_digest_enabled', sa.Boolean(), server_default='true', nullable=True),
    sa.Column('top_match_alerts_enabled', sa.Boolean(), server_default='true', nullable=True),
    sa.Column('signal_alerts_enabled', sa.Boolean(), server_default='true', nullable=True),
    sa.Column('slack_workspace_id', sa.Text(), nullable=True),
    sa.Column('slack_bot_token', sa.Text(), nullable=True),
    sa.Column('slack_channel_id', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=True),
    sa.Column('onboarded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('clerk_org_id'),
    sa.UniqueConstraint('slug')
    )
    op.create_index('idx_firms_clerk_org', 'firms', ['clerk_org_id'], unique=False)
    op.create_index('idx_firms_owner', 'firms', ['owner_user_id'], unique=False)
    op.create_table('firm_embeddings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('firm_id', sa.UUID(), nullable=False),
    sa.Column('source_type', sa.Text(), nullable=False),
    sa.Column('source_id', sa.UUID(), nullable=False),
    sa.Column('related_company_id', sa.UUID(), nullable=True),
    sa.Column('related_sector', sa.Text(), nullable=True),
    sa.Column('related_stage', sa.Text(), nullable=True),
    sa.Column('signal_type', sa.Text(), nullable=True),
    sa.Column('content_text', sa.Text(), nullable=False),
    sa.Column('content_hash', sa.Text(), nullable=False),
    sa.Column('embedding', Vector(1536), nullable=False),
    sa.Column('model_version', sa.Text(), server_default='text-embedding-3-small', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('firm_id IS NOT NULL', name='pool2_requires_firm_id'),
    sa.ForeignKeyConstraint(['firm_id'], ['firms.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['related_company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_firm_embeddings_company', 'firm_embeddings', ['related_company_id'], unique=False)
    op.create_index('idx_firm_embeddings_firm', 'firm_embeddings', ['firm_id'], unique=False)
    op.create_index('idx_firm_embeddings_sector', 'firm_embeddings', ['firm_id', 'related_sector'], unique=False)
    op.create_index('idx_firm_embeddings_source', 'firm_embeddings', ['firm_id', 'source_type'], unique=False)
    op.execute(
        "CREATE INDEX idx_firm_embeddings_vector "
        "ON firm_embeddings USING ivfflat (embedding vector_cosine_ops) "
        "WITH (lists = 100)"
    )
    op.create_table('firm_members',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('firm_id', sa.UUID(), nullable=False),
    sa.Column('clerk_user_id', sa.Text(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('email', sa.Text(), nullable=False),
    sa.Column('role', sa.Text(), nullable=False),
    sa.Column('gmail_connected', sa.Boolean(), server_default='false', nullable=True),
    sa.Column('gmail_access_token', sa.Text(), nullable=True),
    sa.Column('gmail_refresh_token', sa.Text(), nullable=True),
    sa.Column('gmail_token_expiry', sa.DateTime(timezone=True), nullable=True),
    sa.Column('gmail_last_synced', sa.DateTime(timezone=True), nullable=True),
    sa.Column('gmail_email', sa.Text(), nullable=True),
    sa.Column('calendar_connected', sa.Boolean(), server_default='false', nullable=True),
    sa.Column('calendar_access_token', sa.Text(), nullable=True),
    sa.Column('calendar_refresh_token', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=True),
    sa.Column('joined_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['firm_id'], ['firms.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('clerk_user_id')
    )
    op.create_index('idx_firm_members_clerk', 'firm_members', ['clerk_user_id'], unique=False)
    op.create_index('idx_firm_members_firm', 'firm_members', ['firm_id'], unique=False)
    op.create_table('firm_companies',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('firm_id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('pipeline_stage', sa.Text(), server_default='watching', nullable=False),
    sa.Column('pipeline_entered_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('fit_score', sa.SmallInteger(), nullable=True),
    sa.Column('fit_score_rationale', sa.Text(), nullable=True),
    sa.Column('ai_nativeness_score', sa.SmallInteger(), nullable=True),
    sa.Column('analyst_fit_score', sa.SmallInteger(), nullable=True),
    sa.Column('analyst_override_reason', sa.Text(), nullable=True),
    sa.Column('overridden_by', sa.UUID(), nullable=True),
    sa.Column('overridden_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('passed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('pass_category', sa.Text(), nullable=True),
    sa.Column('pass_reason_official', sa.Text(), nullable=True),
    sa.Column('pass_reason_internal', sa.Text(), nullable=True),
    sa.Column('pass_what_would_change', sa.Text(), nullable=True),
    sa.Column('conviction_level', sa.Text(), nullable=True),
    sa.Column('champion_member_id', sa.UUID(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('internal_memo', sa.Text(), nullable=True),
    sa.Column('first_outreach_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_outreach_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('outreach_method', sa.Text(), nullable=True),
    sa.Column('intro_path', sa.Text(), nullable=True),
    sa.Column('previously_seen', sa.Boolean(), server_default='false', nullable=True),
    sa.Column('previous_pass_id', sa.UUID(), nullable=True),
    sa.Column('last_researched_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('research_status', sa.Text(), server_default='pending', nullable=True),
    sa.Column('added_by', sa.UUID(), nullable=True),
    sa.Column('added_source', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['added_by'], ['firm_members.id'], ),
    sa.ForeignKeyConstraint(['champion_member_id'], ['firm_members.id'], ),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['firm_id'], ['firms.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['overridden_by'], ['firm_members.id'], ),
    sa.ForeignKeyConstraint(['previous_pass_id'], ['firm_companies.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('firm_id', 'company_id')
    )
    op.create_index('idx_firm_companies_company', 'firm_companies', ['company_id'], unique=False)
    op.create_index('idx_firm_companies_firm', 'firm_companies', ['firm_id'], unique=False)
    op.create_index('idx_firm_companies_fit', 'firm_companies', ['firm_id', 'fit_score'], unique=False)
    op.create_index('idx_firm_companies_stage', 'firm_companies', ['firm_id', 'pipeline_stage'], unique=False)
    op.create_table('firm_notifications',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('firm_id', sa.UUID(), nullable=False),
    sa.Column('member_id', sa.UUID(), nullable=True),
    sa.Column('notification_type', sa.Text(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('related_company_id', sa.UUID(), nullable=True),
    sa.Column('related_event_id', sa.UUID(), nullable=True),
    sa.Column('delivered_in_app', sa.Boolean(), server_default='false', nullable=True),
    sa.Column('delivered_via_slack', sa.Boolean(), server_default='false', nullable=True),
    sa.Column('delivered_via_email', sa.Boolean(), server_default='false', nullable=True),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('acted_on_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['firm_id'], ['firms.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['member_id'], ['firm_members.id'], ),
    sa.ForeignKeyConstraint(['related_company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_notifications_firm', 'firm_notifications', ['firm_id'], unique=False)
    op.create_index('idx_notifications_unread', 'firm_notifications', ['firm_id', 'read_at'], unique=False, postgresql_where=sa.text('read_at IS NULL'))
    op.create_table('interactions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('firm_id', sa.UUID(), nullable=False),
    sa.Column('firm_company_id', sa.UUID(), nullable=False),
    sa.Column('member_id', sa.UUID(), nullable=True),
    sa.Column('interaction_type', sa.Text(), nullable=False),
    sa.Column('raw_content', sa.Text(), nullable=True),
    sa.Column('subject', sa.Text(), nullable=True),
    sa.Column('participants', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('direction', sa.Text(), nullable=True),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('duration_minutes', sa.Integer(), nullable=True),
    sa.Column('source', sa.Text(), nullable=False),
    sa.Column('gmail_message_id', sa.Text(), nullable=True),
    sa.Column('calendar_event_id', sa.Text(), nullable=True),
    sa.Column('transcript_url', sa.Text(), nullable=True),
    sa.Column('extraction_status', sa.Text(), server_default='pending', nullable=True),
    sa.Column('extracted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('overall_sentiment', sa.Text(), nullable=True),
    sa.Column('conviction_delta', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['firm_company_id'], ['firm_companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['firm_id'], ['firms.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['member_id'], ['firm_members.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_interactions_extraction', 'interactions', ['extraction_status'], unique=False, postgresql_where=sa.text("extraction_status = 'pending'"))
    op.create_index('idx_interactions_firm', 'interactions', ['firm_id'], unique=False)
    op.create_index('idx_interactions_firm_company', 'interactions', ['firm_company_id'], unique=False)
    op.create_index('idx_interactions_occurred', 'interactions', ['occurred_at'], unique=False)
    op.create_index('idx_interactions_type', 'interactions', ['firm_id', 'interaction_type'], unique=False)
    op.create_table('investment_memos',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('firm_id', sa.UUID(), nullable=False),
    sa.Column('firm_company_id', sa.UUID(), nullable=False),
    sa.Column('version', sa.Integer(), server_default='1', nullable=False),
    sa.Column('positioning', sa.Text(), nullable=True),
    sa.Column('what_they_do', sa.Text(), nullable=True),
    sa.Column('market_timing', sa.Text(), nullable=True),
    sa.Column('fit_score', sa.SmallInteger(), nullable=True),
    sa.Column('fit_rationale', sa.Text(), nullable=True),
    sa.Column('thesis_alignment', sa.Text(), nullable=True),
    sa.Column('thesis_gaps', sa.Text(), nullable=True),
    sa.Column('traction_signals', sa.Text(), nullable=True),
    sa.Column('team_assessment', sa.Text(), nullable=True),
    sa.Column('competitive_landscape', sa.Text(), nullable=True),
    sa.Column('risks', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('comparables', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('bull_case', sa.Text(), nullable=True),
    sa.Column('recommended_next_step', sa.Text(), nullable=True),
    sa.Column('conviction_level', sa.Text(), nullable=True),
    sa.Column('pool1_records_used', sa.Integer(), nullable=True),
    sa.Column('pool2_records_used', sa.Integer(), nullable=True),
    sa.Column('pool2_signals_used', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('model_used', sa.Text(), server_default='claude-sonnet-4-5', nullable=False),
    sa.Column('generated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('analyst_rating', sa.SmallInteger(), nullable=True),
    sa.Column('analyst_notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['firm_company_id'], ['firm_companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['firm_id'], ['firms.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('firm_company_id', 'version')
    )
    op.create_index('idx_memos_firm', 'investment_memos', ['firm_id'], unique=False)
    op.create_index('idx_memos_firm_company', 'investment_memos', ['firm_company_id'], unique=False)
    op.create_table('outreach_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('firm_id', sa.UUID(), nullable=False),
    sa.Column('firm_company_id', sa.UUID(), nullable=False),
    sa.Column('member_id', sa.UUID(), nullable=True),
    sa.Column('outreach_type', sa.Text(), nullable=False),
    sa.Column('intro_via', sa.Text(), nullable=True),
    sa.Column('intro_relationship', sa.Text(), nullable=True),
    sa.Column('thesis_framing', sa.Text(), nullable=True),
    sa.Column('first_question', sa.Text(), nullable=True),
    sa.Column('founder_responded', sa.Boolean(), server_default='false', nullable=True),
    sa.Column('response_hours', sa.Integer(), nullable=True),
    sa.Column('founder_response_tone', sa.Text(), nullable=True),
    sa.Column('resulted_in_call', sa.Boolean(), server_default='false', nullable=True),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('responded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['firm_company_id'], ['firm_companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['firm_id'], ['firms.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['member_id'], ['firm_members.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_outreach_firm', 'outreach_events', ['firm_id'], unique=False)
    op.create_index('idx_outreach_firm_company', 'outreach_events', ['firm_company_id'], unique=False)
    op.create_table('pipeline_stage_transitions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('firm_id', sa.UUID(), nullable=False),
    sa.Column('firm_company_id', sa.UUID(), nullable=False),
    sa.Column('from_stage', sa.Text(), nullable=True),
    sa.Column('to_stage', sa.Text(), nullable=False),
    sa.Column('transitioned_by', sa.UUID(), nullable=True),
    sa.Column('transition_type', sa.Text(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('days_in_prior_stage', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['firm_company_id'], ['firm_companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['firm_id'], ['firms.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['transitioned_by'], ['firm_members.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_transitions_created', 'pipeline_stage_transitions', ['created_at'], unique=False)
    op.create_index('idx_transitions_firm', 'pipeline_stage_transitions', ['firm_id'], unique=False)
    op.create_index('idx_transitions_firm_company', 'pipeline_stage_transitions', ['firm_company_id'], unique=False)
    op.create_table('score_deltas',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('firm_id', sa.UUID(), nullable=False),
    sa.Column('firm_company_id', sa.UUID(), nullable=False),
    sa.Column('member_id', sa.UUID(), nullable=True),
    sa.Column('delta_type', sa.Text(), nullable=False),
    sa.Column('reidar_value', sa.Text(), nullable=False),
    sa.Column('human_value', sa.Text(), nullable=False),
    sa.Column('delta_direction', sa.Text(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('context_at_time', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['firm_company_id'], ['firm_companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['firm_id'], ['firms.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['member_id'], ['firm_members.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_score_deltas_firm', 'score_deltas', ['firm_id'], unique=False)
    op.create_index('idx_score_deltas_type', 'score_deltas', ['firm_id', 'delta_type'], unique=False)
    op.create_table('slack_messages',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('firm_id', sa.UUID(), nullable=False),
    sa.Column('member_id', sa.UUID(), nullable=True),
    sa.Column('slack_message_id', sa.Text(), nullable=False),
    sa.Column('slack_channel_id', sa.Text(), nullable=False),
    sa.Column('slack_channel_name', sa.Text(), nullable=True),
    sa.Column('slack_thread_ts', sa.Text(), nullable=True),
    sa.Column('slack_user_id', sa.Text(), nullable=True),
    sa.Column('raw_content', sa.Text(), nullable=False),
    sa.Column('message_type', sa.Text(), nullable=False),
    sa.Column('firm_company_id', sa.UUID(), nullable=True),
    sa.Column('company_id', sa.UUID(), nullable=True),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('extraction_status', sa.Text(), server_default='pending', nullable=True),
    sa.Column('extracted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('detected_sentiment', sa.Text(), nullable=True),
    sa.Column('detected_conviction', sa.Text(), nullable=True),
    sa.Column('mentions_company', sa.Boolean(), server_default='false', nullable=True),
    sa.Column('mentions_founder', sa.Boolean(), server_default='false', nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['firm_company_id'], ['firm_companies.id'], ),
    sa.ForeignKeyConstraint(['firm_id'], ['firms.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['member_id'], ['firm_members.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slack_message_id')
    )
    op.create_index('idx_slack_messages_company', 'slack_messages', ['firm_company_id'], unique=False, postgresql_where=sa.text('firm_company_id IS NOT NULL'))
    op.create_index('idx_slack_messages_extraction', 'slack_messages', ['extraction_status'], unique=False, postgresql_where=sa.text("extraction_status = 'pending'"))
    op.create_index('idx_slack_messages_firm', 'slack_messages', ['firm_id'], unique=False)
    op.create_index('idx_slack_messages_sent', 'slack_messages', ['sent_at'], unique=False)
    op.create_index('idx_slack_messages_type', 'slack_messages', ['firm_id', 'message_type'], unique=False)
    op.create_table('calendar_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('firm_id', sa.UUID(), nullable=False),
    sa.Column('member_id', sa.UUID(), nullable=False),
    sa.Column('calendar_event_id', sa.Text(), nullable=False),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('location', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_minutes', sa.Integer(), nullable=True),
    sa.Column('attendees', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_recurring', sa.Boolean(), server_default='false', nullable=True),
    sa.Column('recurrence_rule', sa.Text(), nullable=True),
    sa.Column('recurrence_parent_id', sa.UUID(), nullable=True),
    sa.Column('matching_status', sa.Text(), server_default='pending', nullable=True),
    sa.Column('matched_company_id', sa.UUID(), nullable=True),
    sa.Column('matched_firm_company_id', sa.UUID(), nullable=True),
    sa.Column('match_confidence', sa.Text(), nullable=True),
    sa.Column('interaction_id', sa.UUID(), nullable=True),
    sa.Column('source', sa.Text(), server_default='google_calendar', nullable=False),
    sa.Column('raw_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['firm_id'], ['firms.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['interaction_id'], ['interactions.id'], ),
    sa.ForeignKeyConstraint(['matched_company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['matched_firm_company_id'], ['firm_companies.id'], ),
    sa.ForeignKeyConstraint(['member_id'], ['firm_members.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['recurrence_parent_id'], ['calendar_events.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_calendar_events_company', 'calendar_events', ['matched_company_id'], unique=False, postgresql_where=sa.text('matched_company_id IS NOT NULL'))
    op.create_index('idx_calendar_events_firm', 'calendar_events', ['firm_id'], unique=False)
    op.create_index('idx_calendar_events_matching', 'calendar_events', ['matching_status'], unique=False, postgresql_where=sa.text("matching_status = 'pending'"))
    op.create_index('idx_calendar_events_member', 'calendar_events', ['member_id'], unique=False)
    op.create_index('idx_calendar_events_started', 'calendar_events', ['started_at'], unique=False)
    op.create_table('documents',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('firm_id', sa.UUID(), nullable=False),
    sa.Column('firm_company_id', sa.UUID(), nullable=True),
    sa.Column('document_type', sa.Text(), nullable=False),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('file_name', sa.Text(), nullable=True),
    sa.Column('file_size_bytes', sa.Integer(), nullable=True),
    sa.Column('mime_type', sa.Text(), nullable=True),
    sa.Column('source', sa.Text(), nullable=False),
    sa.Column('source_interaction_id', sa.UUID(), nullable=True),
    sa.Column('source_slack_message_id', sa.UUID(), nullable=True),
    sa.Column('storage_url', sa.Text(), nullable=True),
    sa.Column('content_hash', sa.Text(), nullable=True),
    sa.Column('first_opened_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_opened_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('open_count', sa.Integer(), server_default='0', nullable=True),
    sa.Column('forwarded_to', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('re_requested', sa.Boolean(), server_default='false', nullable=True),
    sa.Column('extraction_status', sa.Text(), server_default='pending', nullable=True),
    sa.Column('extracted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('extracted_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('received_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['firm_company_id'], ['firm_companies.id'], ),
    sa.ForeignKeyConstraint(['firm_id'], ['firms.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_interaction_id'], ['interactions.id'], ),
    sa.ForeignKeyConstraint(['source_slack_message_id'], ['slack_messages.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_documents_extraction', 'documents', ['extraction_status'], unique=False, postgresql_where=sa.text("extraction_status = 'pending'"))
    op.create_index('idx_documents_firm', 'documents', ['firm_id'], unique=False)
    op.create_index('idx_documents_firm_company', 'documents', ['firm_company_id'], unique=False, postgresql_where=sa.text('firm_company_id IS NOT NULL'))
    op.create_index('idx_documents_received', 'documents', ['received_at'], unique=False)
    op.create_index('idx_documents_type', 'documents', ['firm_id', 'document_type'], unique=False)
    op.create_table('firm_reasoning_signals',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('firm_id', sa.UUID(), nullable=False),
    sa.Column('interaction_id', sa.UUID(), nullable=True),
    sa.Column('firm_company_id', sa.UUID(), nullable=True),
    sa.Column('signal_type', sa.Text(), nullable=False),
    sa.Column('entity_type', sa.Text(), nullable=True),
    sa.Column('entity_id', sa.UUID(), nullable=True),
    sa.Column('structured_data', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('signal_text', sa.Text(), nullable=False),
    sa.Column('confidence', sa.Text(), server_default='medium', nullable=True),
    sa.Column('extraction_model', sa.Text(), server_default='claude-haiku-4-5-20251001', nullable=True),
    sa.Column('signal_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['firm_company_id'], ['firm_companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['firm_id'], ['firms.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['interaction_id'], ['interactions.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_reasoning_signals_company', 'firm_reasoning_signals', ['firm_company_id'], unique=False)
    op.create_index('idx_reasoning_signals_entity', 'firm_reasoning_signals', ['entity_id'], unique=False)
    op.create_index('idx_reasoning_signals_firm', 'firm_reasoning_signals', ['firm_id'], unique=False)
    op.create_index('idx_reasoning_signals_type', 'firm_reasoning_signals', ['firm_id', 'signal_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_reasoning_signals_type', table_name='firm_reasoning_signals')
    op.drop_index('idx_reasoning_signals_firm', table_name='firm_reasoning_signals')
    op.drop_index('idx_reasoning_signals_entity', table_name='firm_reasoning_signals')
    op.drop_index('idx_reasoning_signals_company', table_name='firm_reasoning_signals')
    op.drop_table('firm_reasoning_signals')
    op.drop_index('idx_documents_type', table_name='documents')
    op.drop_index('idx_documents_received', table_name='documents')
    op.drop_index('idx_documents_firm_company', table_name='documents', postgresql_where=sa.text('firm_company_id IS NOT NULL'))
    op.drop_index('idx_documents_firm', table_name='documents')
    op.drop_index('idx_documents_extraction', table_name='documents', postgresql_where=sa.text("extraction_status = 'pending'"))
    op.drop_table('documents')
    op.drop_index('idx_calendar_events_started', table_name='calendar_events')
    op.drop_index('idx_calendar_events_member', table_name='calendar_events')
    op.drop_index('idx_calendar_events_matching', table_name='calendar_events', postgresql_where=sa.text("matching_status = 'pending'"))
    op.drop_index('idx_calendar_events_firm', table_name='calendar_events')
    op.drop_index('idx_calendar_events_company', table_name='calendar_events', postgresql_where=sa.text('matched_company_id IS NOT NULL'))
    op.drop_table('calendar_events')
    op.drop_index('idx_slack_messages_type', table_name='slack_messages')
    op.drop_index('idx_slack_messages_sent', table_name='slack_messages')
    op.drop_index('idx_slack_messages_firm', table_name='slack_messages')
    op.drop_index('idx_slack_messages_extraction', table_name='slack_messages', postgresql_where=sa.text("extraction_status = 'pending'"))
    op.drop_index('idx_slack_messages_company', table_name='slack_messages', postgresql_where=sa.text('firm_company_id IS NOT NULL'))
    op.drop_table('slack_messages')
    op.drop_index('idx_score_deltas_type', table_name='score_deltas')
    op.drop_index('idx_score_deltas_firm', table_name='score_deltas')
    op.drop_table('score_deltas')
    op.drop_index('idx_transitions_firm_company', table_name='pipeline_stage_transitions')
    op.drop_index('idx_transitions_firm', table_name='pipeline_stage_transitions')
    op.drop_index('idx_transitions_created', table_name='pipeline_stage_transitions')
    op.drop_table('pipeline_stage_transitions')
    op.drop_index('idx_outreach_firm_company', table_name='outreach_events')
    op.drop_index('idx_outreach_firm', table_name='outreach_events')
    op.drop_table('outreach_events')
    op.drop_index('idx_memos_firm_company', table_name='investment_memos')
    op.drop_index('idx_memos_firm', table_name='investment_memos')
    op.drop_table('investment_memos')
    op.drop_index('idx_interactions_type', table_name='interactions')
    op.drop_index('idx_interactions_occurred', table_name='interactions')
    op.drop_index('idx_interactions_firm_company', table_name='interactions')
    op.drop_index('idx_interactions_firm', table_name='interactions')
    op.drop_index('idx_interactions_extraction', table_name='interactions', postgresql_where=sa.text("extraction_status = 'pending'"))
    op.drop_table('interactions')
    op.drop_index('idx_notifications_unread', table_name='firm_notifications', postgresql_where=sa.text('read_at IS NULL'))
    op.drop_index('idx_notifications_firm', table_name='firm_notifications')
    op.drop_table('firm_notifications')
    op.drop_index('idx_firm_companies_stage', table_name='firm_companies')
    op.drop_index('idx_firm_companies_fit', table_name='firm_companies')
    op.drop_index('idx_firm_companies_firm', table_name='firm_companies')
    op.drop_index('idx_firm_companies_company', table_name='firm_companies')
    op.drop_table('firm_companies')
    op.drop_index('idx_firm_members_firm', table_name='firm_members')
    op.drop_index('idx_firm_members_clerk', table_name='firm_members')
    op.drop_table('firm_members')
    op.drop_index('idx_firm_embeddings_source', table_name='firm_embeddings')
    op.drop_index('idx_firm_embeddings_sector', table_name='firm_embeddings')
    op.drop_index('idx_firm_embeddings_firm', table_name='firm_embeddings')
    op.drop_index('idx_firm_embeddings_company', table_name='firm_embeddings')
    op.execute("DROP INDEX IF EXISTS idx_firm_embeddings_vector")
    op.drop_table('firm_embeddings')
    op.drop_index('idx_firms_owner', table_name='firms')
    op.drop_index('idx_firms_clerk_org', table_name='firms')
    op.drop_table('firms')
    # ### end Alembic commands ###
