"""layer2_individual_intelligence_layer

Revision ID: 3edbd1cc20ec
Revises: 0da24644e00d
Create Date: 2026-04-12 13:47:56.751219

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3edbd1cc20ec'
down_revision: Union[str, Sequence[str], None] = '0da24644e00d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('firm_members', sa.Column('personal_thesis', sa.Text(), nullable=True))
    op.add_column('firm_members', sa.Column('focus_sectors', postgresql.ARRAY(sa.Text()), server_default='{}', nullable=False))
    op.add_column('firm_members', sa.Column('conviction_patterns', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False))
    op.add_column('firm_reasoning_signals', sa.Column('member_id', sa.UUID(), nullable=True))
    op.create_index('idx_reasoning_signals_member', 'firm_reasoning_signals', ['member_id'], unique=False, postgresql_where=sa.text('member_id IS NOT NULL'))
    op.create_foreign_key('fk_firm_reasoning_signals_member_id', 'firm_reasoning_signals', 'firm_members', ['member_id'], ['id'], ondelete='CASCADE')
    op.add_column('firms', sa.Column('decision_structure', sa.Text(), server_default='partnership', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('firms', 'decision_structure')
    op.drop_constraint('fk_firm_reasoning_signals_member_id', 'firm_reasoning_signals', type_='foreignkey')
    op.drop_index('idx_reasoning_signals_member', table_name='firm_reasoning_signals', postgresql_where=sa.text('member_id IS NOT NULL'))
    op.drop_column('firm_reasoning_signals', 'member_id')
    op.drop_column('firm_members', 'conviction_patterns')
    op.drop_column('firm_members', 'focus_sectors')
    op.drop_column('firm_members', 'personal_thesis')
    # ### end Alembic commands ###
