"""layer1_global_knowledge_base

Revision ID: d623b43ffd99
Revises: 
Create Date: 2026-04-10 17:52:26.522627

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd623b43ffd99'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('companies',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('slug', sa.Text(), nullable=False),
    sa.Column('website', sa.Text(), nullable=True),
    sa.Column('domain', sa.Text(), nullable=True),
    sa.Column('one_liner', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('business_model', sa.Text(), nullable=True),
    sa.Column('target_customer', sa.Text(), nullable=True),
    sa.Column('sector', sa.Text(), nullable=True),
    sa.Column('subsector', sa.Text(), nullable=True),
    sa.Column('tags', postgresql.ARRAY(sa.Text()), nullable=True),
    sa.Column('ai_nativeness', sa.SmallInteger(), nullable=True),
    sa.Column('stage', sa.Text(), nullable=True),
    sa.Column('total_raised_usd', sa.BigInteger(), nullable=True),
    sa.Column('last_round_type', sa.Text(), nullable=True),
    sa.Column('last_round_usd', sa.BigInteger(), nullable=True),
    sa.Column('last_round_date', sa.Date(), nullable=True),
    sa.Column('valuation_usd', sa.BigInteger(), nullable=True),
    sa.Column('employee_count', sa.Integer(), nullable=True),
    sa.Column('founding_year', sa.Integer(), nullable=True),
    sa.Column('headquarters', sa.Text(), nullable=True),
    sa.Column('source', sa.Text(), nullable=False),
    sa.Column('source_url', sa.Text(), nullable=True),
    sa.Column('source_batch', sa.Text(), nullable=True),
    sa.Column('harmonic_id', sa.Text(), nullable=True),
    sa.Column('yc_id', sa.Text(), nullable=True),
    sa.Column('enrichment_status', sa.Text(), nullable=True),
    sa.Column('last_enriched_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('founded_at', sa.Date(), nullable=True),
    sa.Column('scraped_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_index('idx_companies_created_at', 'companies', ['created_at'], unique=False)
    op.create_index('idx_companies_domain', 'companies', ['domain'], unique=False)
    op.create_index('idx_companies_sector', 'companies', ['sector'], unique=False)
    op.create_index('idx_companies_source', 'companies', ['source'], unique=False)
    op.create_index('idx_companies_stage', 'companies', ['stage'], unique=False)
    op.create_table('founders',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('email', sa.Text(), nullable=True),
    sa.Column('linkedin_url', sa.Text(), nullable=True),
    sa.Column('twitter_url', sa.Text(), nullable=True),
    sa.Column('prior_companies', postgresql.ARRAY(sa.Text()), nullable=True),
    sa.Column('prior_roles', postgresql.ARRAY(sa.Text()), nullable=True),
    sa.Column('education', postgresql.ARRAY(sa.Text()), nullable=True),
    sa.Column('domain_years', sa.Integer(), nullable=True),
    sa.Column('prior_exits', sa.Boolean(), nullable=True),
    sa.Column('repeat_founder', sa.Boolean(), nullable=True),
    sa.Column('technical', sa.Boolean(), nullable=True),
    sa.Column('domain_expert', sa.Boolean(), nullable=True),
    sa.Column('source', sa.Text(), nullable=True),
    sa.Column('source_url', sa.Text(), nullable=True),
    sa.Column('scraped_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('investors',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('type', sa.Text(), nullable=True),
    sa.Column('tier', sa.SmallInteger(), nullable=True),
    sa.Column('focus_stages', postgresql.ARRAY(sa.Text()), nullable=True),
    sa.Column('focus_sectors', postgresql.ARRAY(sa.Text()), nullable=True),
    sa.Column('website', sa.Text(), nullable=True),
    sa.Column('crunchbase_url', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('company_embeddings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('firm_id', sa.UUID(), nullable=True),
    sa.Column('embedding_type', sa.Text(), nullable=False),
    sa.Column('content_hash', sa.Text(), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=1536), nullable=False),
    sa.Column('model_version', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('firm_id IS NULL', name='pool1_no_firm_id'),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_company_embeddings_company', 'company_embeddings', ['company_id'], unique=False)
    op.create_index('idx_company_embeddings_type', 'company_embeddings', ['embedding_type'], unique=False)
    op.execute(
        "CREATE INDEX idx_company_embeddings_vector "
        "ON company_embeddings USING ivfflat (embedding vector_cosine_ops) "
        "WITH (lists = 100)"
    )
    op.create_table('company_founders',
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('founder_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.Text(), nullable=True),
    sa.Column('is_primary', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['founder_id'], ['founders.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('company_id', 'founder_id')
    )
    op.create_table('funding_rounds',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('round_type', sa.Text(), nullable=False),
    sa.Column('amount_usd', sa.BigInteger(), nullable=True),
    sa.Column('valuation_usd', sa.BigInteger(), nullable=True),
    sa.Column('announced_date', sa.Date(), nullable=True),
    sa.Column('closed_date', sa.Date(), nullable=True),
    sa.Column('lead_investor', sa.Text(), nullable=True),
    sa.Column('notable_investors', postgresql.ARRAY(sa.Text()), nullable=True),
    sa.Column('source_url', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_funding_rounds_company', 'funding_rounds', ['company_id'], unique=False)
    op.create_index('idx_funding_rounds_date', 'funding_rounds', ['announced_date'], unique=False)
    op.create_table('global_signals',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('signal_type', sa.Text(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('source_url', sa.Text(), nullable=False),
    sa.Column('source_name', sa.Text(), nullable=True),
    sa.Column('signal_strength', sa.SmallInteger(), nullable=True),
    sa.Column('sentiment', sa.Text(), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('detected_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_global_signals_company', 'global_signals', ['company_id'], unique=False)
    op.create_index('idx_global_signals_detected', 'global_signals', ['detected_at'], unique=False)
    op.create_index('idx_global_signals_type', 'global_signals', ['signal_type'], unique=False)
    op.create_table('round_investors',
    sa.Column('round_id', sa.UUID(), nullable=False),
    sa.Column('investor_id', sa.UUID(), nullable=False),
    sa.Column('is_lead', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['investor_id'], ['investors.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['round_id'], ['funding_rounds.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('round_id', 'investor_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('round_investors')
    op.drop_index('idx_global_signals_type', table_name='global_signals')
    op.drop_index('idx_global_signals_detected', table_name='global_signals')
    op.drop_index('idx_global_signals_company', table_name='global_signals')
    op.drop_table('global_signals')
    op.drop_index('idx_funding_rounds_date', table_name='funding_rounds')
    op.drop_index('idx_funding_rounds_company', table_name='funding_rounds')
    op.drop_table('funding_rounds')
    op.drop_table('company_founders')
    op.execute("DROP INDEX IF EXISTS idx_company_embeddings_vector")
    op.drop_index('idx_company_embeddings_type', table_name='company_embeddings')
    op.drop_index('idx_company_embeddings_company', table_name='company_embeddings')
    op.drop_table('company_embeddings')
    op.drop_table('investors')
    op.drop_table('founders')
    op.drop_index('idx_companies_stage', table_name='companies')
    op.drop_index('idx_companies_source', table_name='companies')
    op.drop_index('idx_companies_sector', table_name='companies')
    op.drop_index('idx_companies_domain', table_name='companies')
    op.drop_index('idx_companies_created_at', table_name='companies')
    op.drop_table('companies')
    # ### end Alembic commands ###
